#pragma once

enum class ServiceStatus
{
    SUCCESS,
    NOT_FOUND,
    INVALID_PASSWORD,
    ALREADY_EXISTS,
    USER_ALREADY_LOGGED_IN,
    USER_NOT_LOGGED_IN,
    PERMISSION_DENIED,
    INVALID_INPUT,
    OPERATION_FAILED,
};
